spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group1
      auto-offset-reset: earliest

  redis:
    host: localhost
    port: 6379

server:
  port: 8080

logging:
  file:
    name: ./logs/app.log
